set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse
set -g mouse on

# Set custom prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Theme
set -g @tokyo-night-tmux_theme night    # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 1  # 1 = transparent | 0 = solid (default)

# Number styles
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

# Custom window icons
#set -g @tokyo-night-tmux_terminal_icon        # icon for inactive windows (default: )
#set -g @tokyo-night-tmux_active_terminal_icon   # icon for the active window (default: )

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0  # 1 = no extra space | 0 = add space (default)

# Date and Time widget
set -g @tokyo-night-tmux_show_datetime 1  # 1 = enabled (default) | 0 = disabled
set -g @tokyo-night-tmux_date_format YMD
set -g @tokyo-night-tmux_time_format 12H

# Now Playing widget
set -g @tokyo-night-tmux_show_music 1

# Path Widget
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'

# Local and Web Git status
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_wbg 1

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi

# Keybindings
## Vim like yanking
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

## Reload the tmux configuration
bind r source-file ~/.tmux.conf \; display-message " Tmux config reloaded!"

## Clear history & screen 
bind b send-keys -R C-l \; clear-history

## Open panes in current directory
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %
